# 01-postgres-secret.yaml
#
# This Kubernetes Secret stores the PostgreSQL database password securely.
# It uses the 'Opaque' type, meaning the data is base64 encoded.
# Always replace 'your_secure_password' with a strong, unique password.
#
# To create the base64 encoded password:
# echo -n "your_secure_password" | base64
#
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret # Name of the secret
  labels:
    app: postgres # Label for easy identification
type: Opaque # Type of the secret. 'Opaque' is default.
data:
  # The password for the PostgreSQL database.
  # Replace 'eW91cl9zZWN1cmVfcGFzc3dvcmQ=' with the base64 encoded version
  # of your actual database password.
  # Example: echo -n "myStrongDBPassword" | base64
  POSTGRES_PASSWORD: eW91cl9zZWN1cmVfcGFzc3dvcmQ= # Base64 encoded 'your_secure_password'
